export const ACTIVE_GENERATION_STATUSES = [
  "queued",
  "preparing",
  "downloading_model",
  "initializing_pipeline",
  "generating_script",
  "tts",
  "tts_synthesizing",
  "tts_done",
  "transcribing",
  "transcribe_done",
  "generating_subtitles",
  "subtitles_done",
  "selecting_background",
  "compositing",
  "ffmpeg_processing",
  "compositing_done",
  "thumbnail",
  "generating_thumbnail",
  "uploading",
  "cleanup",
  "processing",
];

export const STATUS_CONFIG: Record<string, { label: string; color: string; bgColor: string }> = {
  queued: { label: "Queued", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  preparing: { label: "Preparing", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  downloading_model: { label: "Downloading Model", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  initializing_pipeline: { label: "Initializing", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  generating_script: { label: "Script", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  tts: { label: "TTS", color: "text-purple-600", bgColor: "bg-purple-100 dark:bg-purple-900/30" },
  tts_synthesizing: { label: "Synthesizing", color: "text-purple-600", bgColor: "bg-purple-100 dark:bg-purple-900/30" },
  tts_done: { label: "TTS Done", color: "text-purple-600", bgColor: "bg-purple-100 dark:bg-purple-900/30" },
  transcribing: { label: "Transcribing", color: "text-indigo-600", bgColor: "bg-indigo-100 dark:bg-indigo-900/30" },
  transcribe_done: { label: "Transcribed", color: "text-indigo-600", bgColor: "bg-indigo-100 dark:bg-indigo-900/30" },
  generating_subtitles: { label: "Subtitles", color: "text-indigo-600", bgColor: "bg-indigo-100 dark:bg-indigo-900/30" },
  subtitles_done: { label: "Subtitles Done", color: "text-indigo-600", bgColor: "bg-indigo-100 dark:bg-indigo-900/30" },
  selecting_background: { label: "Background", color: "text-cyan-600", bgColor: "bg-cyan-100 dark:bg-cyan-900/30" },
  compositing: { label: "Compositing", color: "text-orange-600", bgColor: "bg-orange-100 dark:bg-orange-900/30" },
  ffmpeg_processing: { label: "FFmpeg", color: "text-orange-600", bgColor: "bg-orange-100 dark:bg-orange-900/30" },
  compositing_done: { label: "Finalizing", color: "text-orange-600", bgColor: "bg-orange-100 dark:bg-orange-900/30" },
  thumbnail: { label: "Thumbnail", color: "text-pink-600", bgColor: "bg-pink-100 dark:bg-pink-900/30" },
  generating_thumbnail: { label: "Thumbnail", color: "text-pink-600", bgColor: "bg-pink-100 dark:bg-pink-900/30" },
  uploading: { label: "Uploading", color: "text-green-600", bgColor: "bg-green-100 dark:bg-green-900/30" },
  cleanup: { label: "Cleanup", color: "text-gray-600", bgColor: "bg-gray-100 dark:bg-gray-900/30" },
  processing: { label: "Processing", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  done: { label: "Done", color: "text-green-600", bgColor: "bg-green-100 dark:bg-green-900/30" },
  failed: { label: "Failed", color: "text-red-600", bgColor: "bg-red-100 dark:bg-red-900/30" },
  cancelled: { label: "Cancelled", color: "text-gray-600", bgColor: "bg-gray-100 dark:bg-gray-900/30" },
  paused: { label: "Paused", color: "text-yellow-600", bgColor: "bg-yellow-100 dark:bg-yellow-900/30" },
};

export const YT_STATUS_CONFIG: Record<string, { label: string; color: string; bgColor: string }> = {
  not_uploaded: { label: "Not Uploaded", color: "text-gray-600", bgColor: "bg-gray-100 dark:bg-gray-900/30" },
  uploaded: { label: "Uploaded", color: "text-green-600", bgColor: "bg-green-100 dark:bg-green-900/30" },
  uploading: { label: "Uploading", color: "text-blue-600", bgColor: "bg-blue-100 dark:bg-blue-900/30" },
  failed: { label: "Upload Failed", color: "text-red-600", bgColor: "bg-red-100 dark:bg-red-900/30" },
  private: { label: "Private", color: "text-yellow-600", bgColor: "bg-yellow-100 dark:bg-yellow-900/30" },
  public: { label: "Public", color: "text-green-600", bgColor: "bg-green-100 dark:bg-green-900/30" },
  unlisted: { label: "Unlisted", color: "text-purple-600", bgColor: "bg-purple-100 dark:bg-purple-900/30" },
};
